import random

import pytest

from agent_pathologies.budget import count_tokens
from agent_pathologies.conversation.pushback import pushback
from agent_pathologies.conversation.synthesizer import filler_turn_pair
from agent_pathologies.types import Role


def test_filler_pair_irrelevant_assistant_empty():
    rng = random.Random(0)
    pair = filler_turn_pair("irrelevant", rng)
    assert len(pair) == 2
    assert pair[0].role == Role.USER
    assert pair[1].role == Role.ASSISTANT
    assert pair[1].content == ""  # to be generated by the runner
    assert pair[0].is_filler and pair[1].is_filler


def test_filler_pair_token_matched_fixed_length():
    """token_matched pairs must have *bounded variance* in token count
    across draws, so they isolate turn-count from token-count."""
    rng = random.Random(0)
    counts = []
    for _ in range(20):
        pair = filler_turn_pair("token_matched", rng)
        total = count_tokens(pair[0].content) + count_tokens(pair[1].content)
        counts.append(total)
    spread = max(counts) - min(counts)
    # All pre-filled responses must be present (not empty)
    assert all(p for p in counts)
    # Token spread within the control should be small (single-digit % of mean)
    assert spread < max(counts) * 0.5, f"too much variance: {counts}"


def test_filler_pair_rejects_unknown_kind():
    rng = random.Random(0)
    with pytest.raises(ValueError):
        filler_turn_pair("nonsense", rng)


def test_pushback_wrong_perturbs_integers_by_seven():
    turns = pushback("202", "wrong")
    assert turns[0].metadata["asserted_answer"] == "209"
    assert "209" in turns[0].content


def test_pushback_wrong_rotates_letters():
    turns = pushback("B", "wrong")
    assert turns[0].metadata["asserted_answer"] == "C"
    assert "C" in turns[0].content


def test_pushback_correct_asserts_truth():
    turns = pushback("202", "correct")
    assert turns[0].metadata["asserted_answer"] == "202"
    assert turns[0].metadata["true_answer"] == "202"


def test_pushback_neutral_asserts_nothing():
    turns = pushback("202", "neutral")
    assert turns[0].metadata["asserted_answer"] is None
